window.PORTFOLIO_CONTENT = {
  es: {
    "nav.home":"Inicio","nav.about":"Sobre mí","nav.stack":"Stack","nav.projects":"Proyectos","nav.experience":"Experiencia","nav.contact":"Contacto",
    "hero.eyebrow":"Desarrollo web · Frontend & Backend","hero.role":"Desarrollador Full Stack Junior","hero.lead":"Técnico Superior en DAM y DAW. Perfil junior full stack con experiencia práctica en desarrollo web, frontend Angular/React y backend Java/Spring.","hero.projects":"Ver proyectos","hero.cv":"Descargar CV","hero.location":"Tenerife, España",
    "about.kicker":"Perfil","about.title":"Desarrollo soluciones web de extremo a extremo.","about.body":"Técnico Superior en DAM y DAW. Perfil junior full stack con experiencia práctica en desarrollo web, frontend Angular/React y backend Java/Spring. Orientado al aprendizaje continuo, al trabajo en equipo y a construir soluciones mantenibles y útiles para el usuario.","about.point1.title":"Full stack","about.point1.text":"Cómodo moviéndome entre frontend, backend y datos según lo requiera el proyecto.","about.point2.title":"Trabajo en equipo","about.point2.text":"Experiencia práctica en entornos reales, con foco en comunicación, mantenimiento y colaboración.","about.point3.title":"Aprendizaje continuo","about.point3.text":"Me adapto a nuevas tecnologías y entornos sin cerrarme a un único stack.",
    "stack.kicker":"Tecnologías","stack.title":"Stack técnico","stack.subtitle":"Tecnologías con las que he trabajado en formación, proyectos y experiencia profesional.","stack.frontend":"Frontend","stack.backend":"Backend","stack.databases":"Bases de datos","stack.tools":"Herramientas / otros",
    "projects.kicker":"Trabajo seleccionado","projects.title":"Proyectos destacados","projects.subtitle":"Una selección orientada a mostrar distintos tipos de problemas, stacks y responsabilidades.","projects.featured":"Proyecto destacado","projects.game.summary":"Aplicación web full stack para registrar y analizar sesiones de juego, explorar videojuegos y participar en una comunidad con reseñas y favoritos.","projects.game.f1":"Login con email o Steam.","projects.game.f2":"Historial de sesiones, estadísticas y gráficos interactivos.","projects.game.f3":"RAWG, Game Detail, favoritos, reseñas y Community Hub.","projects.inventory.title":"Control de inventario y stock","projects.inventory.summary":"TFG / proyecto intermodular para gestionar inventario y stock conectando software con dispositivos y servicios externos.","projects.inventory.f1":"Integración con Open Food Facts.","projects.inventory.f2":"Lectura de peso mediante báscula por puerto COM.","projects.inventory.f3":"Escáner de códigos QR y códigos de barras.","projects.inventory.private":"Proyecto académico · sin repositorio público","projects.jayuwoki.summary":"Bot de Discord con aplicación de escritorio para crear equipos, gestionar jugadores, una tabla de puntuación Elo y distintos comandos.","projects.jayuwoki.f1":"Privaditas 5v5 y sistema Elo.","projects.jayuwoki.f2":"CRUD de jugadores y estadísticas.","projects.jayuwoki.f3":"Java 22, JavaFX, JDA, Firebase Firestore y Maven.","projects.repo":"Ver repositorio",
    "experience.kicker":"Trayectoria","experience.title":"Experiencia y formación","experience.subtitle":"Experiencia práctica en desarrollo web y dos titulaciones superiores enfocadas a software.","experience.label":"Experiencia profesional","experience.laberit.role":"Programador Junior Full Stack · Prácticas","experience.laberit.context":"Proyecto para la Generalitat Valenciana · entorno de administración pública","experience.laberit.b1":"Desarrollo y mantenimiento de funcionalidades frontend y backend.","experience.laberit.b2":"DTOs, servicios, repositorios, controladores REST y lógica de negocio con Java, Spring y JPA/Hibernate.","experience.laberit.b3":"Angular/TypeScript con formularios reactivos, datatables, wizards y componentes ARQ SDK.","experience.laberit.b4":"Postman, Oracle, SVN, Maven, WildFly/JBoss e IntelliJ IDEA.","experience.digital7.role":"Desarrollador de páginas web · Prácticas","experience.digital7.b1":"Diseño y desarrollo de sitios web personalizados con WordPress.","experience.digital7.b2":"Configuración y optimización de plugins y temas.","experience.digital7.b3":"Mantenimiento, actualización y mejoras SEO.",
    "education.label":"Formación","education.daw.title":"Técnico Superior en Desarrollo de Aplicaciones Web","education.dam.title":"Técnico Superior en Desarrollo de Aplicaciones Multiplataforma","education.english":"Inglés B1 certificado · uso profesional en documentación técnica, herramientas y entornos de desarrollo.",
    "contact.kicker":"Hablemos","contact.title":"¿Tienes un proyecto o una oportunidad?","contact.subtitle":"Puedes escribirme directamente o utilizar el formulario.","contact.locationLabel":"Ubicación","contact.form.name":"Nombre","contact.form.email":"Email","contact.form.message":"Mensaje","contact.form.namePlaceholder":"Tu nombre","contact.form.emailPlaceholder":"tu@email.com","contact.form.messagePlaceholder":"Cuéntame brevemente en qué puedo ayudarte","contact.form.submit":"Enviar mensaje","contact.form.sending":"Enviando…","contact.form.required":"Completa todos los campos.","contact.form.invalidEmail":"Introduce un email válido.","contact.form.success":"Mensaje enviado correctamente. Te responderé pronto.","contact.form.error":"No se pudo enviar el mensaje. Puedes escribirme directamente por email.","footer.copy":"Diseñado y desarrollado por Jorge A. Herrero Santana.","footer.back":"Volver arriba"
  },
  en: {
    "nav.home":"Home","nav.about":"About","nav.stack":"Stack","nav.projects":"Projects","nav.experience":"Experience","nav.contact":"Contact",
    "hero.eyebrow":"Web development · Frontend & Backend","hero.role":"Junior Full Stack Developer","hero.lead":"Higher Technician in Multiplatform and Web Application Development. Junior full stack profile with hands-on experience in web development, Angular/React frontend and Java/Spring backend.","hero.projects":"View projects","hero.cv":"Download CV","hero.location":"Tenerife, Spain",
    "about.kicker":"Profile","about.title":"I build web solutions from end to end.","about.body":"Higher Technician in Multiplatform and Web Application Development. Junior full stack profile with hands-on experience in web development, Angular/React frontend and Java/Spring backend. Focused on continuous learning, teamwork and building maintainable solutions that are useful to users.","about.point1.title":"Full stack","about.point1.text":"Comfortable moving between frontend, backend and data depending on the project.","about.point2.title":"Teamwork","about.point2.text":"Hands-on experience in real environments, with a focus on communication, maintenance and collaboration.","about.point3.title":"Continuous learning","about.point3.text":"I adapt to new technologies and environments instead of limiting myself to one stack.",
    "stack.kicker":"Technologies","stack.title":"Technical stack","stack.subtitle":"Technologies I have used through education, projects and professional experience.","stack.frontend":"Frontend","stack.backend":"Backend","stack.databases":"Databases","stack.tools":"Tools / other",
    "projects.kicker":"Selected work","projects.title":"Featured projects","projects.subtitle":"A selection focused on showing different problems, stacks and responsibilities.","projects.featured":"Featured project","projects.game.summary":"Full-stack web application to log and analyze gaming sessions, explore video games and take part in a community with reviews and favorites.","projects.game.f1":"Email or Steam login.","projects.game.f2":"Session history, statistics and interactive charts.","projects.game.f3":"RAWG, Game Detail, favorites, reviews and Community Hub.","projects.inventory.title":"Inventory and stock control","projects.inventory.summary":"Capstone / intermodular project for inventory and stock management, connecting software with devices and external services.","projects.inventory.f1":"Open Food Facts integration.","projects.inventory.f2":"Weight readings from a scale through a COM port.","projects.inventory.f3":"QR and barcode scanning.","projects.inventory.private":"Academic project · no public repository","projects.jayuwoki.summary":"Discord bot with a desktop app to create teams, manage players, an Elo score table and several commands.","projects.jayuwoki.f1":"5v5 private matches and Elo system.","projects.jayuwoki.f2":"Player CRUD and statistics.","projects.jayuwoki.f3":"Java 22, JavaFX, JDA, Firebase Firestore and Maven.","projects.repo":"View repository",
    "experience.kicker":"Background","experience.title":"Experience & education","experience.subtitle":"Hands-on web development experience and two higher vocational qualifications focused on software.","experience.label":"Professional experience","experience.laberit.role":"Junior Full Stack Developer · Internship","experience.laberit.context":"Project for Generalitat Valenciana · public administration environment","experience.laberit.b1":"Development and maintenance of frontend and backend features.","experience.laberit.b2":"DTOs, services, repositories, REST controllers and business logic with Java, Spring and JPA/Hibernate.","experience.laberit.b3":"Angular/TypeScript with reactive forms, datatables, wizards and ARQ SDK components.","experience.laberit.b4":"Postman, Oracle, SVN, Maven, WildFly/JBoss and IntelliJ IDEA.","experience.digital7.role":"Web Developer · Internship","experience.digital7.b1":"Design and development of custom WordPress websites.","experience.digital7.b2":"Plugin and theme configuration and optimization.","experience.digital7.b3":"Maintenance, updates and SEO improvements.",
    "education.label":"Education","education.daw.title":"Higher Technician in Web Application Development","education.dam.title":"Higher Technician in Multiplatform Application Development","education.english":"Certified B1 English · professional use in technical documentation, tools and development environments.",
    "contact.kicker":"Let's talk","contact.title":"Have a project or an opportunity?","contact.subtitle":"You can email me directly or use the form.","contact.locationLabel":"Location","contact.form.name":"Name","contact.form.email":"Email","contact.form.message":"Message","contact.form.namePlaceholder":"Your name","contact.form.emailPlaceholder":"you@email.com","contact.form.messagePlaceholder":"Tell me briefly how I can help","contact.form.submit":"Send message","contact.form.sending":"Sending…","contact.form.required":"Please complete all fields.","contact.form.invalidEmail":"Please enter a valid email address.","contact.form.success":"Message sent successfully. I will get back to you soon.","contact.form.error":"The message could not be sent. You can email me directly instead.","footer.copy":"Designed and developed by Jorge A. Herrero Santana.","footer.back":"Back to top"
  }
};
